# Generated by Django 4.2.5 on 2023-10-24 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrivate', models.BooleanField(default=False)),
                ('inviteCode', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('docId', models.CharField(blank=True, max_length=24, null=True)),
                ('heading', models.CharField(max_length=64)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
            options={
                'permissions': [('can_comment', 'Can comment'), ('can_edit', 'Can Edit')],
            },
        ),
    ]
