# Generated by Django 4.2.5 on 2023-11-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetext',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
