# Generated by Django 4.2.5 on 2023-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_filetext_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetext',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
